### ISSUE TITLE
Error opening device. Unknown, busy or no permissions

### ISSUE THREAD

**Issue by bluemanos** [pajikos/sms-gammu-gateway#12]
I run your project in docker, but it cant start.

```txt
Traceback (most recent call last):,
  File "./run.py", line 12, in <module>,
    machine = init_state_machine(pin),
  File "/sms-gw/support.py", line 18, in init_state_machine,
    sm.Init(),
gammu.ERR_DEVICEOPENERROR: {'Text': 'Error opening device. Unknown, busy or no permissions.', 'Where': 'Init', 'Code': 2},
```
Device is correctly mapped: `/dev/ttyUSB1:/dev/mobile`
My `.gammurc` also is using the device:
```$ cat ~/.gammurc 
[gammu]
device = /dev/ttyUSB1
connection = at
```

Any idea what to do, how to fix it?

**Comment by pajikos** [comment]
Unfortunately, it is a common behavior when gammu sometimes locks your gsm modem, something bad happened in gammu and after container restart, it cannot be used again. 
Re-inserting USB modem or restart your machine usually helps to unlock the modem. This is the simplest, but I know, not so good solution, but not found any better yet.
Anyway, it cannot be solved inside this python wrapper gateway.

**Comment by Mitschli** [comment]
Hi

I would like to revisit this issue. After some time of trouble-free operation, I installed the latest Ubuntu server on my system. Unfortunately, the Docker container has not been running since then, which means that SMS alerts via HA are no longer possible.

```
File "/sms-gw/support.py", line 18, in init_state_machine

    sm.Init()

gammu.ERR_DEVICEOPENERROR: {'Text': 'Error opening device. Unknown, busy or no permissions.', 'Where': 'Init', 'Code': 2}

Traceback (most recent call last):

  File "/sms-gw/./run.py", line 14, in <module>

    machine = init_state_machine(pin)

```
My docker compose config...

```
sms-gammu-gateway:
    container_name: sms-gammu-gateway
    restart: always
    image: pajikos/sms-gammu-gateway
    volumes:
      - ./sms-gammu-gateway:/data
    environment:
      - PIN=""
    ports:
      - "5000:5000"
    devices:
      - /dev/ttyUSB2:/dev/mobile
```   

I have restarted the computer several times and recreated the Docker container, but unfortunately nothing works.
The SIM card is fine; it works in my cell phone without any problems.
Does anyone have any other ideas I could try? 
Thanks!
